#!/usr/bin/env bash
# Usage:
#   Step 1 — fetch manifest + samplesheet only (no files downloaded):
#     bash fetch_member_accessions.sh --member 2
#     bash fetch_member_accessions.sh --member 2 --accessions ENCSR000AKC,ENCSR000AKJ
#
#   Step 2 — same command with --download to also pull the FASTQ files:
#     bash fetch_member_accessions.sh --member 2 --download
#     bash fetch_member_accessions.sh --member 2 --accessions ENCSR000AKC,ENCSR000AKJ --download

set -euo pipefail

# ── defaults ──────────────────────────────────────────────────────────────────
MEMBER=""
CUSTOM_ACCESSIONS=""
DOWNLOAD=false

# ── arg parsing ───────────────────────────────────────────────────────────────
usage() {
  echo "Usage: bash $(basename "$0") [--member <1-5|all>] [--accessions ACC1,ACC2,...] [--download]"
  echo ""
  echo "  --member       Optional. 1-5 to fetch one member's slice; 'all' or omitted"
  echo "                 to fetch the union of all 5 members (~913 accessions)."
  echo "  --accessions   Optional. Override with a specific comma-separated accession list."
  echo "  --download     Optional. Also download the FASTQ files (omit for manifest-only)."
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --member)      MEMBER="$2";            shift 2 ;;
    --accessions)  CUSTOM_ACCESSIONS="$2"; shift 2 ;;
    --download)    DOWNLOAD=true;          shift   ;;
    -h|--help)     usage ;;
    *) echo "Unknown option: $1"; usage ;;
  esac
done

# Default: no --member means "all" (union of every memberN.txt).
[[ -z "$MEMBER" ]] && MEMBER="all"

# Resolve script-relative paths (used for member list + later cd into raw/).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── load accession list ──────────────────────────────────────────────────────
# Lists live in members/memberN.txt (one ENCSR ID per line). Generated by
# tools/compute_member_split.py, which keeps each member's ChIP assignments
# as-is and aligns the controls so every ChIP's matched controls live in the
# same member's file (no orphan controls, no missing controls).
if ! [[ "$MEMBER" =~ ^([1-5]|all)$ ]]; then
  echo "ERROR: --member must be 1-5 or 'all'."
  usage
fi

# MEMBER == "all" → no --accessions filter; encodefetch's search filters
# (assay-title + target-label + organism) match every released H3K27ac
# Histone ChIP-seq, which is the full ~913-experiment dataset.
ACCESSIONS=""
if [[ "$MEMBER" != "all" ]]; then
  MEMBER_FILE="${SCRIPT_DIR}/members/member${MEMBER}.txt"
  [[ -f "$MEMBER_FILE" ]] || {
    echo "ERROR: $MEMBER_FILE not found."
    echo "       Run: python3 ${SCRIPT_DIR}/tools/compute_member_split.py"
    exit 1
  }
  ACCESSIONS=$(paste -sd, "$MEMBER_FILE")
fi

# override with custom accessions if provided
if [[ -n "$CUSTOM_ACCESSIONS" ]]; then
  ACCESSIONS="$CUSTOM_ACCESSIONS"
fi

if [[ -z "$ACCESSIONS" ]]; then
  echo "Member ${MEMBER}: no --accessions filter (full released H3K27ac dataset)"
elif [[ -n "$CUSTOM_ACCESSIONS" ]]; then
  COUNT=$(echo "$CUSTOM_ACCESSIONS" | tr ',' '\n' | wc -l)
  echo "Member ${MEMBER}: using custom accession list (${COUNT} accessions)"
else
  COUNT=$(grep -c '^ENCSR' "$MEMBER_FILE")
  echo "Member ${MEMBER}: using pre-assigned accession list (${COUNT} accessions)"
fi

if $DOWNLOAD; then
  echo "Mode: fetch manifest + samplesheet + download FASTQ files"
else
  echo "Mode: fetch manifest + samplesheet only  (re-run with --download to also pull FASTQ files)"
fi
echo ""

# ── run from the raw/ directory ────────────────────────────────────────────────
cd "${SCRIPT_DIR}/raw" || { echo "ERROR: could not cd into raw/"; exit 1; }

DOWNLOAD_FLAG=""
if $DOWNLOAD; then
  DOWNLOAD_FLAG="--download"
fi

# When MEMBER=all (and no custom override), $ACCESSIONS is empty, so we omit
# --accessions entirely and let encodefetch's search filters return everything.
ACCESSIONS_FLAG=()
if [[ -n "$ACCESSIONS" ]]; then
  ACCESSIONS_FLAG=(--accessions "$ACCESSIONS")
fi

echo "Running command:"
echo "  encodefetch \\"
[[ -n "$ACCESSIONS" ]] && echo "    --accessions \"${ACCESSIONS}\" \\"
echo "    --assay-title \"Histone ChIP-seq\" \\"
echo "    --target-label H3K27ac \\"
echo "    --organism \"Homo sapiens\" \\"
echo "    --file-type fastq \\"
echo "    --status released \\"
echo "    --threads 10 \\"
echo "    --progress \\"
echo "    --nfcore ${DOWNLOAD_FLAG}"
echo ""
echo "Please wait while it runs in the background..."

encodefetch \
  "${ACCESSIONS_FLAG[@]}" \
  --assay-title "Histone ChIP-seq" \
  --target-label H3K27ac \
  --organism "Homo sapiens" \
  --file-type fastq \
  --status released \
  --threads 10 \
  --progress \
  --nfcore \
  ${DOWNLOAD_FLAG}
