#!/bin/bash
# ------------------------------------------------------------------------------
# SLURM driver for Enhancerflow (super-enhancer calling on chipseq output).
#
# Pipeline order:
#   1. activate micromamba env 'dbsuper_pipeline'
#   2. make_enhancerflow_samplesheet.py
#        chipseq samplesheet + chipseq out/ → enhancerflow_samplesheet.csv
#   3. nextflow run khan-lab/enhancerflow ...
#
# Layout (everything stays under Enhancerflow/):
#   logs/driver/      — driver job stdout/err
#   logs/samplesheet/ — make_enhancerflow_samplesheet.py logs
#   logs/nextflow/    — Nextflow .nextflow.log
#   logs/reports/     — trace/report/timeline/dag (set by nextflow.slurm.config)
#   out/              — Enhancerflow --outdir
#
# Usage:
#   sbatch submit_enhancerflow.sh                       # member1 (default)
#   sbatch submit_enhancerflow.sh --member 2
#   sbatch submit_enhancerflow.sh --member all
#   sbatch submit_enhancerflow.sh --member 1 --skip-samplesheet
#
# Driver sizing rationale: Nextflow's executor is 'slurm' (see
# nextflow.slurm.config), so all real compute is dispatched as child sbatch
# jobs on compute nodes. The driver only runs the Nextflow JVM + the python
# samplesheet step → 4 CPUs, 8 GB is plenty (validated empirically — JVM RES
# typically <2 GB, 4 GB peak).
# ------------------------------------------------------------------------------

#SBATCH --job-name=nf-enhancerflow
#SBATCH --partition=cpu
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G
#SBATCH --time=7-00:00:00
#SBATCH -o logs/driver/driver-%x-%j.log
#SBATCH -e logs/driver/driver-%x-%j.err

set -euo pipefail

# ── parse args ────────────────────────────────────────────────────────────────
MEMBER="all"
SKIP_SAMPLESHEET=false
GENOME="mm10"

usage() {
  echo "Usage: sbatch $(basename "$0") [--member <1-5|all>] [--genome KEY] [--skip-samplesheet]"
  echo ""
  echo "  --member            which chipseq output to consume (default: all)"
  echo "                      maps to ../out/member<N> (or ../out/all)"
  echo "  --genome            assembly passed to ROSE2 + rGREAT (default: mm10)"
  echo "  --skip-samplesheet  reuse the existing enhancerflow_samplesheet.csv"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --member)            MEMBER="$2";       shift 2 ;;
    --genome)            GENOME="$2";       shift 2 ;;
    --skip-samplesheet)  SKIP_SAMPLESHEET=true; shift ;;
    -h|--help)           usage ;;
    *) echo "Unknown option: $1"; usage ;;
  esac
done

# ── project layout ────────────────────────────────────────────────────────────
# Under sbatch, $SLURM_SUBMIT_DIR is the dir you ran sbatch from. We expect
# that to be Enhancerflow/. Falls back to BASH_SOURCE for manual `bash` runs.
ENHANCERFLOW_DIR="${SLURM_SUBMIT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
cd "$ENHANCERFLOW_DIR"

if [[ "$MEMBER" == "all" ]]; then
  CHIPSEQ_OUTDIR="../out/all"
else
  CHIPSEQ_OUTDIR="../out/member${MEMBER}"
fi
CHIPSEQ_SAMPLESHEET="../raw/encode_results/nfcore_chipseq_samplesheet.local.csv"
SAMPLESHEET="enhancerflow_samplesheet.csv"

TS="$(date +%Y%m%d-%H%M%S)"
mkdir -p logs/driver logs/samplesheet logs/nextflow logs/reports out

SAMPLESHEET_LOG="logs/samplesheet/samplesheet-${MEMBER}-${TS}.log"

echo "[$(date)] === enhancerflow driver start ==="
echo "  enhancerflow_dir : $ENHANCERFLOW_DIR"
echo "  member           : $MEMBER"
echo "  genome           : $GENOME"
echo "  chipseq_outdir   : $CHIPSEQ_OUTDIR"
echo "  samplesheet_out  : $SAMPLESHEET"
echo "  skip-samplesheet : $SKIP_SAMPLESHEET"
echo "  timestamp        : $TS"

# ── 1. activate dbsuper_pipeline environment ──────────────────────────────────
echo "[$(date)] activating micromamba env 'dbsuper_pipeline'"
set +u
export MAMBA_ROOT_PREFIX="/storage/software/micromamba"
eval "$(/usr/local/bin/micromamba shell hook --shell bash)" \
  || { echo "Could not init micromamba; check /usr/local/bin/micromamba"; exit 1; }
micromamba activate dbsuper_pipeline
set -u

# ── 2. make_enhancerflow_samplesheet.py ──────────────────────────────────────
# The samplesheet is now generated by walking the per-sample staging dir
# produced upstream by `sbatch submit_staging.sh`. Each subdir of staging/
# becomes one row.
STAGING_DIR="staging"
if $SKIP_SAMPLESHEET; then
  echo "[$(date)] --skip-samplesheet given; reusing existing $SAMPLESHEET"
  [[ -f "$SAMPLESHEET" ]] || { echo "ERROR: $SAMPLESHEET not found"; exit 1; }
else
  [[ -d "$STAGING_DIR" ]] || {
    echo "ERROR: staging dir not found at $STAGING_DIR — run "
    echo "       'sbatch submit_staging.sh' first to populate it"; exit 1; }

  echo "[$(date)] running make_enhancerflow_samplesheet.py -> $SAMPLESHEET_LOG"
  python3 make_enhancerflow_samplesheet.py \
    --staging-dir "$STAGING_DIR" \
    --condition   H3K27ac \
    --absolute \
    >"$SAMPLESHEET_LOG" 2>&1

  [[ -s "$SAMPLESHEET" ]] || { echo "ERROR: $SAMPLESHEET empty"; exit 1; }
fi

# ── 3. nextflow run ───────────────────────────────────────────────────────────
CONFIG="nextflow.slurm.config"
[[ -f "$CONFIG" ]] || { echo "ERROR: missing $CONFIG"; exit 1; }

echo "[$(date)] launching khan-lab/enhancerflow"
echo "  samplesheet : $SAMPLESHEET"
echo "  config      : $CONFIG"
echo "  outdir      : out/"

# Track upstream main. `nextflow pull` (run beforehand or via -latest) refreshes
# the local asset cache; resolved SHA is logged below for traceability.
ENHANCERFLOW_REV="main"
echo "  enhancerflow rev: $ENHANCERFLOW_REV (resolving to current main)"

# --genome ($GENOME, default mm10) is the assembly name passed to ROSE2 (-g)
# and (when enabled) rGREAT. --fasta overrides the iGenomes S3 URL (compute
# nodes can't reach it) with the local FASTA that nf-core/chipseq published —
# the same reference the staged BAMs were aligned to, so coordinates match.
# Skips:
#   --skip_homer  HOMER off (FIMO/SEA motif analysis still runs)
#   --skip_great  GREAT off: the rgreat container ships only the human TxDb,
#                 not TxDb.Mmusculus.UCSC.mm10.knownGene, so GREAT local mode
#                 fails on mouse. Drop this flag once the container bundles the
#                 mouse TxDb (+ org.Mm.eg.db).
GENOME_FASTA="$CHIPSEQ_OUTDIR/genome/genome.fa"
[[ -f "$GENOME_FASTA" ]] || { echo "ERROR: genome FASTA not at $GENOME_FASTA"; exit 1; }

nextflow -log logs/nextflow/.nextflow.log \
  run khan-lab/enhancerflow -r "$ENHANCERFLOW_REV" \
  -profile apptainer \
  -c "$CONFIG" \
  -resume \
  --input          "$SAMPLESHEET" \
  --genome         "$GENOME" \
  --fasta          "$GENOME_FASTA" \
  --outdir         out/ \
  --skip_crc \
  --skip_comparison \
  --skip_homer \
  # --skip_great
  
echo "[$(date)] driver exit status: $?"
